### ISSUE TITLE
rgb666 divider in vc4_dsi.c file

### ISSUE THREAD

**Issue by mbt28** [anholt/linux#132]
Hi,

In vc4_dsi.c at line 1302, the case MIPI_DSI_FMT_RGB666. Divider is set to 24 but shouldnt  it be 18?

I check some other linux dsi drivers for this format they specify 18bit.

**Comment by anholt** [comment]
RGB666 is 6 bits each, packed into a 24-bit pixel with dummy bits in between.  See mipi_dsi_pixel_format_to_bpp(), which we ought to be using instead of our own mapping.
