### ISSUE TITLE
twivc4 blogging stopped in 2018

### ISSUE THREAD

**Issue by fanoush** [anholt/linux#148]
I reached this issue tracker via https://anholt.github.io/twivc4/

It looks like last blog is dated Dec 10, 2018. Maybe the blogging AI bot needs restart or adding some scheduled jobs for 2019? ;-)

BTW dont take this too seriously please and thanks for everything Eric, it is a sad year without your Videocore blog updates :-)

**Comment by anholt** [comment]
Please don't hassle me about a thing I chose to do in my spare time and don't have time for.

**Comment by fanoush** [comment]
Oh, I apologise once again. It was not meant to be annoying. Sorry about that.
