### ISSUE TITLE
vc4: missing gamma ramp support

### ISSUE THREAD

**Issue by anholt** [anholt/linux#15]
Possibly related to a note about washed out colors in openarena.

**Comment by ric96** [comment]
+1

**Comment by randyoo** [comment]
+1
I realize this isn't a support forum, but would this explain why xgamma seems to have no effect for me?

**Comment by anholt** [comment]
@randyoo yes, this would be why

**Comment by anholt** [comment]
Patch submitted upstream.

**Comment by anholt** [comment]
Merged to airlied/drm-next
