### ISSUE TITLE
vc4: Queue V3D bin/render jobs in parallel

### ISSUE THREAD

**Issue by anholt** [anholt/linux#16]
Varad has been working on taking my anholt/vc4-kms-v3d-rpi2-binrendersubmit-2 branch and fixing it.  Hopefully done soon.

**Comment by varadgautam** [comment]
patch up for review at [https://patchwork.kernel.org/patch/8339021/](https://patchwork.kernel.org/patch/8339021/)

**Comment by anholt** [comment]
Merged:

commit ca26d28bbaa39f31d5e7e4812603b015c8d54207
Author: Varad Gautam varadgautam@gmail.com
Date:   Wed Feb 17 19:08:21 2016 +0530

```
drm/vc4: improve throughput by pipelining binning and rendering jobs
```
