### ISSUE TITLE
A DT available for Raspberry Pi 3?

### ISSUE THREAD

**Issue by joaodriessen** [anholt/linux#34]
Want to put the correct DT in config.txt (device_tree=)
But not sure whether there is a specific one for the Raspberry Pi 3 (a specific bcm2837 doesn't seem exist so unsure whether using bcm2836-rpi-2-b.dtb is the right thing to do here)
cheers, JD.

**Comment by anholt** [comment]
Pi3 support for arm64 is in progress on the bcm2837-64-next branch, not yet upstream.  Closing this issue since it's more of a question than a bug report.
