### ISSUE TITLE
vc4 terminal is lost on Raspberry Pi 3 boot

### ISSUE THREAD

**Issue by sirspudd** [anholt/linux#39]
Hola,

Thank you for the awesome work to date. I followed your instructions to get Linux 4.7 compiled and running on the Pi. This works awesome on the Raspberry Pi 2, but the same sd-card blanks on my Raspberry Pi 3 following the:

"Switching to vc4drmfb from simplefb"

My kernel sources have b3a15f6d, which looks like it should address exactly this issue. (The associated description is perfect.)

Please let me know how I can help resolving this

**Comment by anholt** [comment]
This is due to us not having access to the GPIO expander for hotplug detect.  Cherry-picking aa8cbd1ff120c27ce2c3206b1ad57cbf231b4572 from the downstream tree should work around it.

**Comment by sirspudd** [comment]
Thank you, I grabbed an earlier one of your patches from the fedora 24 aarch64 kernel sources and hence have been a happy camper for the last couple weeks.
