### ISSUE TITLE
dtoverlay=vc4-kms-v3d doesn't work with analog video

### ISSUE THREAD

**Issue by grray** [anholt/linux#61]
I enabled experimental OpenGL driver and got black screen on my analog TV, connected to Raspberry pi via RCA cable. Raspberry pi is working and I can login to it via ssh. All is fine, when I connect it to monitor via HDMI cable. Before enabling experimental OpenGL driver all also was good on analog TV. Is it even supposed to work with TV? I'll provide logs, if needed.

**Comment by anholt** [comment]
This is #14, so closing this issue in favor of tracking it there.  You should be able to get analog TV working with the downstream kernel using the `dtoverlay=vc4-fkms-v3d` (with an 'f') for now.
