### ISSUE TITLE
raspberry pi 3 b GL black screen

### ISSUE THREAD

**Issue by jordanwilliams1** [anholt/linux#62]
It seems that when i enable open gl on my pi3 it gives me a blank display every time i boot it up. I've tried to re-install the os and tried 2 different monitors but everytime I get a black screen. How can I fix this?

**Comment by jordanwilliams1** [comment]
using NOOBS os

**Comment by anholt** [comment]
You'll need to attach (not paste) your dmesg, hopefully with drm.debug=0x1f in cmdline.txt.

**Comment by jordanwilliams1** [comment]
It seems to crash on boot up. Not able to ssh to it :/

**Comment by anholt** [comment]
Serial console is generally required for kernel debugging.

**Comment by anholt** [comment]
Closing for now since there's no debug information to work from.  Feel free to reopen if you can get a serial console up.
