### ISSUE TITLE
vchiq: Need a device tree node in upstream kernel tree

### ISSUE THREAD

**Issue by Electron752** [anholt/linux#88]
The TODO list for vchiq has adding a device tree node for vchiq to the upstream device trees.  This would allow vchiq to load without any hacks.  I noticed that this has been added to the camera branch here and as you know is necessary to make the camera driver meaningful.

I would submit the changes to get the device tree for vchiq in, but I know nothing about the process.

I think if vchiq was added to the upstream device tree, the upstream tree would have enough value at that point to make 64 bit on the RPI 3 meaningful and I could easily pull all/most of the 64 bit specific changes from the downstream tree.  That would make 64 bit unsupported on the downstream tree...

**Comment by Electron752** [comment]
I think this topic may be related.

https://github.com/raspberrypi/linux/issues/1843

**Comment by anholt** [comment]
upstream:

```commit 614fa22119d6f406beac500fe30bc5c0b60ec34a
Author: Eric Anholt <eric@anholt.net>
Date:   Fri Mar 9 10:44:15 2018 -0800

    ARM: dts: bcm2835: Add VCHIQ node to the Raspberry Pi boards. (v3)
```
